# Generated by Django 5.2.6 on 2025-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maps', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='branch_img')),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(help_text='Enter multiple phone numbers separated by commas', max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('office_open', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
