# Generated by Django 5.2.6 on 2025-11-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='instagram',
            field=models.URLField(default='https://www.instagram.com/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com/'),
        ),
        migrations.AddField(
            model_name='branch',
            name='twitter',
            field=models.URLField(default='https://www.x.com/'),
        ),
    ]
