# Generated by Django 5.2.6 on 2025-11-03 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_project_done_category'),
        ('contact_app', '0002_branch_facebook_branch_instagram_branch_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('email', models.EmailField(help_text='Enter your email address', max_length=254)),
                ('phone_number', models.CharField(help_text='Enter phone number with country code', max_length=20, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999999999999)])),
                ('message', models.TextField(help_text='Enter your message')),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, help_text='Contact status')),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this contact was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this contact was last updated')),
                ('service', models.ForeignKey(help_text="Select the service you're inquiring about", on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company_app.services')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='contact_app_status_04e919_idx'), models.Index(fields=['is_read'], name='contact_app_is_read_16d71b_idx'), models.Index(fields=['created_at'], name='contact_app_created_2e698f_idx')],
            },
        ),
    ]
