# Generated by Django 5.2.6 on 2025-11-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(help_text='Enter phone number with country code', max_length=20),
        ),
    ]
