# Generated by Django 5.2.6 on 2025-10-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_footer_logo', models.ImageField(blank=True, null=True, upload_to='company_footer_logos/')),
                ('company_favicon', models.ImageField(blank=True, null=True, upload_to='company_favicons/')),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='company_images/')),
                ('company_intro', models.TextField(blank=True, null=True)),
                ('company_mission', models.TextField(blank=True, null=True)),
                ('company_vision', models.TextField(blank=True, null=True)),
                ('company_footer', models.TextField(blank=True, null=True)),
                ('map_iframe', models.TextField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial_images/')),
                ('message', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_done',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='project_done/')),
                ('company', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='company_logo/')),
                ('description', models.TextField()),
                ('live_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('service', models.ForeignKey(help_text='Select a service from the dropdown', on_delete=django.db.models.deletion.CASCADE, to='company_app.services', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Project Done',
                'verbose_name_plural': 'Projects Done',
                'ordering': ['-created_at'],
            },
        ),
    ]
