# Generated by Django 5.2.6 on 2025-10-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_profile',
            options={'permissions': [('manage_company_profile', 'Can manage company profile')]},
        ),
    ]
