# Generated by Django 5.2.6 on 2025-10-13 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0002_alter_company_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the client', max_length=100, verbose_name='Client Name')),
                ('designation', models.CharField(blank=True, help_text="Client's job title or position (optional)", max_length=100, null=True, verbose_name='Designation/Position')),
                ('image', models.ImageField(blank=True, help_text="Upload client's photo (recommended: 200x200px)", null=True, upload_to='services_testimonials/%Y/%m/%d/', verbose_name='Client Photo')),
                ('message', models.TextField(help_text="Share the client's experience and feedback", verbose_name='Testimonial Message')),
                ('rating', models.PositiveIntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], default=5, help_text="Select client's satisfaction rating", verbose_name='Rating')),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, help_text='Toggle to show/hide testimonial', verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service', models.ForeignKey(help_text='Select the service this testimonial is for', on_delete=django.db.models.deletion.CASCADE, to='company_app.services', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Testimonial',
                'verbose_name_plural': 'Service Testimonials',
                'ordering': ['-created_at', 'service'],
                'indexes': [models.Index(fields=['service', 'status'], name='company_app_service_56df01_idx'), models.Index(fields=['rating'], name='company_app_rating_2408ed_idx')],
            },
        ),
    ]
