# Generated by Django 5.2.6 on 2025-10-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0005_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category name (e.g., Web Development, Mobile Apps)', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated)', max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='category/images/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, help_text='Brief description of the category', null=True)),
                ('status', models.BooleanField(default=True, help_text='Whether the category is active and visible', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Higher number appears first', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['-ordering', 'title'],
            },
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
    ]
