# Generated by Django 5.2.6 on 2025-10-16 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0006_category_delete_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_done',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Select a category from the dropdown', null=True, on_delete=django.db.models.deletion.CASCADE, to='company_app.category', verbose_name='category'),
        ),
    ]
