# Generated by Django 5.2.6 on 2025-11-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0007_project_done_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('success', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('service', models.ForeignKey(help_text='Select a service from the dropdown', on_delete=django.db.models.deletion.CASCADE, to='company_app.services', verbose_name='Service')),
            ],
        ),
    ]
