# Generated by Django 5.2.6 on 2025-10-12 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='training_images/')),
                ('duration', models.DurationField()),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('offer_price', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_multi_images/', verbose_name='Image')),
                ('status', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='trainings_app.training')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
