# Generated by Django 5.2.6 on 2025-10-28 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('education', models.CharField(blank=True, choices=[('high_school', 'High School Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True)),
                ('experience', models.CharField(blank=True, choices=[('none', 'No Experience'), ('less_than_1_year', 'Beginner (Less than 1 year)'), ('1_3_years', 'Intermediate (1-3 years)'), ('3_5_years', 'Advanced (3-5 years)'), ('more_than_5_years', 'Expert (More than 5 years)')], max_length=20, null=True)),
                ('source', models.CharField(blank=True, choices=[('friend', 'Friend/Colleague'), ('social_media', 'Social Media'), ('website', 'Website'), ('other', 'Other')], max_length=20, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='course_app.course')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('course', 'email', 'contact_number')},
            },
        ),
    ]
