# Generated by Django 5.2.6 on 2025-10-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_courseenrollment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
    ]
