# Generated by Django 5.2.6 on 2025-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(default='your email', max_length=254),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='full_name',
            field=models.CharField(default='full name', max_length=100),
        ),
    ]
