# Generated by Django 5.2.6 on 2025-10-13 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a descriptive title for the slider (max 255 characters)', max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(help_text='Brief description of the slider content (max 500 characters)', max_length=500, verbose_name='Short Description')),
                ('image', models.ImageField(help_text='Upload slider image (recommended size: 1200x600px)', upload_to='sliders/%Y/%m/%d/', verbose_name='Image')),
                ('link', models.URLField(blank=True, help_text='Optional URL link for the slider', max_length=500, null=True, verbose_name='Link')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Slider status', max_length=10, verbose_name='Status')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which sliders are displayed (lower numbers first)', verbose_name='Display Order')),
                ('target_blank', models.BooleanField(default=False, help_text='Check to open link in new tab/window', verbose_name='Open in new tab')),
                ('start_date', models.DateTimeField(blank=True, help_text='Date when slider becomes active', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Date when slider becomes inactive', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'sliders',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'order'], name='sliders_status_ecbd5a_idx'), models.Index(fields=['created_at'], name='sliders_created_5a25f1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('title',), name='unique_slider_title')],
            },
        ),
    ]
