# Generated by Django 5.2.6 on 2025-10-13 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq_app', '0002_slider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slider',
            new_name='slider_status_20198b_idx',
            old_name='sliders_status_ecbd5a_idx',
        ),
        migrations.RenameIndex(
            model_name='slider',
            new_name='slider_created_3b96b0_idx',
            old_name='sliders_created_5a25f1_idx',
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='slider',
            table='slider',
        ),
    ]
