# Generated by Django 5.2.6 on 2025-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='packages/')),
                ('month_price', models.PositiveIntegerField()),
                ('year_price', models.PositiveIntegerField()),
                ('short_desc', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('graphic_design', models.CharField(max_length=100)),
                ('motion_graphic', models.CharField(max_length=100)),
                ('shute_video', models.CharField(max_length=100)),
                ('content_video', models.CharField(max_length=100)),
                ('real', models.CharField(max_length=100)),
                ('bosting', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('tags', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
    ]
