# Generated by Django 5.2.6 on 2025-11-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_business_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business_category', models.CharField(max_length=200)),
                ('no_of_graphics', models.CharField(max_length=100)),
                ('no_of_videos', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Custom Package',
                'verbose_name_plural': 'Custom Packages',
            },
        ),
    ]
