# Generated by Django 5.2.6 on 2025-11-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0002_custompackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_business_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package_app.package')),
            ],
            options={
                'verbose_name': 'Plan Subscriber',
                'verbose_name_plural': 'Plan Subscriber',
            },
        ),
    ]
