# Generated by Django 5.2.6 on 2025-11-02 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0003_plansubscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plansubscriber',
            old_name='Package',
            new_name='package',
        ),
    ]
