# Generated by Django 5.2.6 on 2025-11-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0004_rename_package_plansubscriber_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='plansubscriber',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
