# Generated by Django 5.2.6 on 2025-11-07 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0005_custompackage_created_at_plansubscriber_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompackage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, upload_to='packages/'),
        ),
        migrations.AlterField(
            model_name='plansubscriber',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
