# Generated by Django 5.2.6 on 2025-11-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0006_alter_custompackage_created_at_alter_package_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='packages/'),
        ),
    ]
