# Generated by Django 5.2.6 on 2025-11-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_app', '0007_alter_package_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
